package com.ficruty.caocap.Database

public val settingAboutActivityContent = listOf<String>(
    "In order for us to provide Meta Products, we must process information about you. The types of information we collect depend on the nature of your use of our products. You can learn how to access and delete the data we collect by visiting Facebook Settings and Instagram Settings .\n" +
            "Things that you and others do and provide information about.\n" +
            "The information and content items you provide. We collect content, communications, and other information you provide when you use our Products, including when you sign up for an account, create or share content, and message and communicate with others. This can include information in or information about that content (such as metadata) such as the location of an image and the date the file was created. It may also include what you see through the features we provide, such as the Camera , where we can do things like suggest masks and filters you might like, or give you tips on using camera formats. Our systems automatically process the content and communications you and others provide to analyze the context and what the content and communications include for the purposes described below . Learn more about how to control who can see your contentwith his participation .\n" +
            "Data with special protections: You can choose to provide information in your Facebook profile fields or personal events about your religious beliefs, political views, “interests” or health. This and similar information (such as origin, ethnicity, philosophical beliefs, or trade association membership) may be subject to special protections under the laws of your country.\n" +
            "Networks and Communications. We collect information about the people, accounts, hashtags , groups and Facebook Pages you connect with and how you interact with them across our Products, such as the people you communicate with most or groups you are in. We also collect contact information if you choose to upload, sync, or import it from a device (such as an address book), call history or SMS history), which we use for things such as helping you and others find people you may know and for the other purposes described below .\n" +
            "your use. We collect information about your use of our products, such as the types of content you view or interact with, features you use, actions you take, people or accounts you interact with, and the times, frequency, and duration of your activities. For example, we record when you use our products, when you last used them, and what types of posts, videos, and other types of content you see on our products. We also collect information related to how you use features such as the camera.\n" +
            "Information related to financial transactions made on our products. If you use our Products to make purchases or other financial transactions (for example, when you make a game purchase or donate ), we collect information about the purchase or transaction. It includes your payment information such as your credit or debit card number, other card information, other account and authentication information, and contact, shipping and billing details.\n" +
            "The things others do and the information they provide about you. We also receive and analyze the content, communications, and information that others provide when they use our Products. This may include information about you, such as when others share a photo of you, comment on it, send you a message, or upload, sync or import your contact information.\n" +
            "Device information\n" +
            "As described below, we collect information from and about the computers, mobile phones, Internet-connected TVs, and other Internet-connected devices you use to access our Products, and we collect this information across the various devices you use. For example, we use information collected about your use of our Products from your phone to better personalize the content (including ads ) or features that appear to you when you use our Products on another device, such as a laptop or tablet, or to measure If you have taken action in response to an advertisement that we have shown you on your phone or other device.\n" +
            "\n" +
            "The information we obtain from these devices includes:\n" +
            "\n" +
            "Device attributes: Information such as the operating system, hardware, software versions, battery level, signal strength, available storage space, browser type, and the names and types of apps, files, and plug-ins.\n" +
            "Device Operations: Information about the operations and behaviors that are performed on the device, for example whether a window is displayed in the foreground or sent to the background, or mouse movements (which can help distinguish human users from automated programs).\n" +
            "Identifiers: Unique identifiers, device identifiers, and other identifiers, such as identifiers for games, apps, or accounts you use, and Family Device identifiers (or other identifiers unique to Meta products associated with the same device or account).\n" +
            "Device signals: Bluetooth signals and information about the nearest Wi-Fi access points, signals, or cell phone towers.\n" +
            "Data from device settings: Information that you allow us to receive from the device settings you turn on, such as accessing your location via GPS, camera, or photos.\n" +
            "Network and Connections: Information such as the name of your mobile operator or Internet service provider, language, time zone, mobile phone number, IP address, Internet connection speed, and, in some cases, information about other devices nearby or connected to the same network as you, so that we can do some Things like helping you stream a video from your phone to your TV .\n" +
            "Cookie data: Data that is stored from cookies on your device, including cookie identifiers and settings. You can learn more about how we use cookies in the Facebook Cookie Policy and the Instagram Cookie Policy .",



    "In order for us to provide Meta Products, we must process information about you. The types of information we collect depend on the nature of your use of our products. You can learn how to access and delete the data we collect by visiting Facebook Settings and Instagram Settings .\n" +
            "Things that you and others do and provide information about.\n" +
            "The information and content items you provide. We collect content, communications, and other information you provide when you use our Products, including when you sign up for an account, create or share content, and message and communicate with others. This can include information in or information about that content (such as metadata) such as the location of an image and the date the file was created. It may also include what you see through the features we provide, such as the Camera , where we can do things like suggest masks and filters you might like, or give you tips on using camera formats. Our systems automatically process the content and communications you and others provide to analyze the context and what the content and communications include for the purposes described below . Learn more about how to control who can see your contentwith his participation .\n" +
            "Data with special protections: You can choose to provide information in your Facebook profile fields or personal events about your religious beliefs, political views, “interests” or health. This and similar information (such as origin, ethnicity, philosophical beliefs, or trade association membership) may be subject to special protections under the laws of your country.\n" +
            "Networks and Communications. We collect information about the people, accounts, hashtags , groups and Facebook Pages you connect with and how you interact with them across our Products, such as the people you communicate with most or groups you are in. We also collect contact information if you choose to upload, sync, or import it from a device (such as an address book), call history or SMS history), which we use for things such as helping you and others find people you may know and for the other purposes described below .\n" +
            "your use. We collect information about your use of our products, such as the types of content you view or interact with, features you use, actions you take, people or accounts you interact with, and the times, frequency, and duration of your activities. For example, we record when you use our products, when you last used them, and what types of posts, videos, and other types of content you see on our products. We also collect information related to how you use features such as the camera.\n" +
            "Information related to financial transactions made on our products. If you use our Products to make purchases or other financial transactions (for example, when you make a game purchase or donate ), we collect information about the purchase or transaction. It includes your payment information such as your credit or debit card number, other card information, other account and authentication information, and contact, shipping and billing details.\n" +
            "The things others do and the information they provide about you. We also receive and analyze the content, communications, and information that others provide when they use our Products. This may include information about you, such as when others share a photo of you, comment on it, send you a message, or upload, sync or import your contact information.\n" +
            "Device information\n" +
            "As described below, we collect information from and about the computers, mobile phones, Internet-connected TVs, and other Internet-connected devices you use to access our Products, and we collect this information across the various devices you use. For example, we use information collected about your use of our Products from your phone to better personalize the content (including ads ) or features that appear to you when you use our Products on another device, such as a laptop or tablet, or to measure If you have taken action in response to an advertisement that we have shown you on your phone or other device.\n" +
            "\n" +
            "The information we obtain from these devices includes:\n" +
            "\n" +
            "Device attributes: Information such as the operating system, hardware, software versions, battery level, signal strength, available storage space, browser type, and the names and types of apps, files, and plug-ins.\n" +
            "Device Operations: Information about the operations and behaviors that are performed on the device, for example whether a window is displayed in the foreground or sent to the background, or mouse movements (which can help distinguish human users from automated programs).\n" +
            "Identifiers: Unique identifiers, device identifiers, and other identifiers, such as identifiers for games, apps, or accounts you use, and Family Device identifiers (or other identifiers unique to Meta products associated with the same device or account).\n" +
            "Device signals: Bluetooth signals and information about the nearest Wi-Fi access points, signals, or cell phone towers.\n" +
            "Data from device settings: Information that you allow us to receive from the device settings you turn on, such as accessing your location via GPS, camera, or photos.\n" +
            "Network and Connections: Information such as the name of your mobile operator or Internet service provider, language, time zone, mobile phone number, IP address, Internet connection speed, and, in some cases, information about other devices nearby or connected to the same network as you, so that we can do some Things like helping you stream a video from your phone to your TV .\n" +
            "Cookie data: Data that is stored from cookies on your device, including cookie identifiers and settings. You can learn more about how we use cookies in the Facebook Cookie Policy and the Instagram Cookie Policy .",



    "In order for us to provide Meta Products, we must process information about you. The types of information we collect depend on the nature of your use of our products. You can learn how to access and delete the data we collect by visiting Facebook Settings and Instagram Settings .\n" +
            "Things that you and others do and provide information about.\n" +
            "The information and content items you provide. We collect content, communications, and other information you provide when you use our Products, including when you sign up for an account, create or share content, and message and communicate with others. This can include information in or information about that content (such as metadata) such as the location of an image and the date the file was created. It may also include what you see through the features we provide, such as the Camera , where we can do things like suggest masks and filters you might like, or give you tips on using camera formats. Our systems automatically process the content and communications you and others provide to analyze the context and what the content and communications include for the purposes described below . Learn more about how to control who can see your contentwith his participation .\n" +
            "Data with special protections: You can choose to provide information in your Facebook profile fields or personal events about your religious beliefs, political views, “interests” or health. This and similar information (such as origin, ethnicity, philosophical beliefs, or trade association membership) may be subject to special protections under the laws of your country.\n" +
            "Networks and Communications. We collect information about the people, accounts, hashtags , groups and Facebook Pages you connect with and how you interact with them across our Products, such as the people you communicate with most or groups you are in. We also collect contact information if you choose to upload, sync, or import it from a device (such as an address book), call history or SMS history), which we use for things such as helping you and others find people you may know and for the other purposes described below .\n" +
            "your use. We collect information about your use of our products, such as the types of content you view or interact with, features you use, actions you take, people or accounts you interact with, and the times, frequency, and duration of your activities. For example, we record when you use our products, when you last used them, and what types of posts, videos, and other types of content you see on our products. We also collect information related to how you use features such as the camera.\n" +
            "Information related to financial transactions made on our products. If you use our Products to make purchases or other financial transactions (for example, when you make a game purchase or donate ), we collect information about the purchase or transaction. It includes your payment information such as your credit or debit card number, other card information, other account and authentication information, and contact, shipping and billing details.\n" +
            "The things others do and the information they provide about you. We also receive and analyze the content, communications, and information that others provide when they use our Products. This may include information about you, such as when others share a photo of you, comment on it, send you a message, or upload, sync or import your contact information.\n" +
            "Device information\n" +
            "As described below, we collect information from and about the computers, mobile phones, Internet-connected TVs, and other Internet-connected devices you use to access our Products, and we collect this information across the various devices you use. For example, we use information collected about your use of our Products from your phone to better personalize the content (including ads ) or features that appear to you when you use our Products on another device, such as a laptop or tablet, or to measure If you have taken action in response to an advertisement that we have shown you on your phone or other device.\n" +
            "\n" +
            "The information we obtain from these devices includes:\n" +
            "\n" +
            "Device attributes: Information such as the operating system, hardware, software versions, battery level, signal strength, available storage space, browser type, and the names and types of apps, files, and plug-ins.\n" +
            "Device Operations: Information about the operations and behaviors that are performed on the device, for example whether a window is displayed in the foreground or sent to the background, or mouse movements (which can help distinguish human users from automated programs).\n" +
            "Identifiers: Unique identifiers, device identifiers, and other identifiers, such as identifiers for games, apps, or accounts you use, and Family Device identifiers (or other identifiers unique to Meta products associated with the same device or account).\n" +
            "Device signals: Bluetooth signals and information about the nearest Wi-Fi access points, signals, or cell phone towers.\n" +
            "Data from device settings: Information that you allow us to receive from the device settings you turn on, such as accessing your location via GPS, camera, or photos.\n" +
            "Network and Connections: Information such as the name of your mobile operator or Internet service provider, language, time zone, mobile phone number, IP address, Internet connection speed, and, in some cases, information about other devices nearby or connected to the same network as you, so that we can do some Things like helping you stream a video from your phone to your TV .\n" +
            "Cookie data: Data that is stored from cookies on your device, including cookie identifiers and settings. You can learn more about how we use cookies in the Facebook Cookie Policy and the Instagram Cookie Policy ."
)

